"""Validate the bandarmologi signal logic on synthetic data.
DuckDB stands in for Snowflake — window/QUALIFY/PERCENT_RANK semantics match.
"""
import duckdb, random
random.seed(7)

con = duckdb.connect()

TICKERS = [f"TK{i:02d}" for i in range(30)]
BROKERS = ["AK", "BK", "CS", "ML", "KZ", "YP", "PD", "CC", "NI", "DX"]
FOREIGN = {"AK", "BK", "CS", "ML", "KZ"}

con.execute("""
CREATE TABLE DAILY_PRICE (TICKER VARCHAR, TRADE_DATE DATE, CLOSE_PRICE DOUBLE,
                          VOLUME_SHARES BIGINT, VALUE_IDR BIGINT);
CREATE TABLE BROKER_SUMMARY (TICKER VARCHAR, TRADE_DATE DATE, BROKER_CODE VARCHAR,
                             BUY_LOT BIGINT, BUY_VALUE BIGINT, SELL_LOT BIGINT, SELL_VALUE BIGINT);
CREATE TABLE BROKER (BROKER_CODE VARCHAR, BROKER_NAME VARCHAR, IS_FOREIGN BOOLEAN, BROKER_TIER VARCHAR);
""")

con.executemany("INSERT INTO BROKER VALUES (?,?,?,?)",
                [(b, f"Broker {b}", b in FOREIGN, "BIG") for b in BROKERS])

prices, brokers_rows = [], []
for t in TICKERS:
    px = random.uniform(200, 5000)
    # give a few tickers a genuine accumulation regime
    accumulating = random.random() < 0.3
    for d in range(120):
        date = f"2026-01-01"
        drift = 0.0015 if accumulating else 0.0
        px *= (1 + random.gauss(drift, 0.02))
        vol = int(random.uniform(1e6, 5e7))
        val = int(px * vol)
        prices.append((t, d, px, vol, val))
        remaining = val
        for i, b in enumerate(BROKERS):
            share = random.uniform(0.03, 0.25)
            gross = int(val * share / 2)
            tilt = 0.35 if (accumulating and b in FOREIGN and i < 3) else 0.0
            buy = int(gross * (0.5 + tilt + random.uniform(-0.1, 0.1)))
            sell = max(gross - buy, 0)
            brokers_rows.append((t, d, b, buy // int(px * 100) + 1, buy,
                                 sell // int(px * 100) + 1, sell))

con.executemany(
    "INSERT INTO DAILY_PRICE VALUES (?, DATE '2026-01-01' + ?, ?, ?, ?)", prices)
con.executemany(
    "INSERT INTO BROKER_SUMMARY VALUES (?, DATE '2026-01-01' + ?, ?, ?, ?, ?, ?)", brokers_rows)

print("rows:", con.execute("SELECT COUNT(*) FROM BROKER_SUMMARY").fetchone()[0])

# ---------- LAYER 1 ----------
con.execute("""
CREATE TABLE FACT_BROKER_NET AS
SELECT bs.TICKER, bs.TRADE_DATE, bs.BROKER_CODE,
       COALESCE(b.IS_FOREIGN, FALSE) AS IS_FOREIGN,
       bs.BUY_VALUE - bs.SELL_VALUE AS NET_VALUE,
       bs.BUY_VALUE + bs.SELL_VALUE AS GROSS_VALUE
FROM BROKER_SUMMARY bs LEFT JOIN BROKER b ON b.BROKER_CODE = bs.BROKER_CODE;
""")

# ---------- LAYER 2a ----------
con.execute("""
CREATE TABLE DAILY_BROKER_AGG AS
WITH totals AS (
  SELECT TICKER, TRADE_DATE,
         SUM(GROSS_VALUE)/2 AS TOTAL_VALUE,
         SUM(CASE WHEN NET_VALUE>0 THEN NET_VALUE ELSE 0 END) AS TOTAL_NET_BUY,
         SUM(CASE WHEN IS_FOREIGN THEN NET_VALUE ELSE 0 END) AS FOREIGN_NET_VALUE
  FROM FACT_BROKER_NET GROUP BY TICKER, TRADE_DATE
), hhi AS (
  SELECT n.TICKER, n.TRADE_DATE,
         SUM(POWER(n.NET_VALUE / NULLIF(t.TOTAL_NET_BUY,0), 2)) AS BUY_HHI
  FROM FACT_BROKER_NET n JOIN totals t USING (TICKER, TRADE_DATE)
  WHERE n.NET_VALUE > 0 GROUP BY n.TICKER, n.TRADE_DATE
), top_buyer AS (
  SELECT TICKER, TRADE_DATE, BROKER_CODE AS TOP_BUYER_CODE, NET_VALUE AS TOP_BUYER_NET_VALUE
  FROM FACT_BROKER_NET
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKER, TRADE_DATE ORDER BY NET_VALUE DESC) = 1
)
SELECT t.*, COALESCE(h.BUY_HHI,0) AS BUY_HHI, tb.TOP_BUYER_CODE,
       tb.TOP_BUYER_NET_VALUE / NULLIF(t.TOTAL_NET_BUY,0) AS TOP_BUYER_SHARE
FROM totals t
LEFT JOIN hhi h USING (TICKER, TRADE_DATE)
LEFT JOIN top_buyer tb USING (TICKER, TRADE_DATE);
""")

# ---------- persistence via self-join (no RANGE INTERVAL) ----------
con.execute("""
CREATE TABLE TOP_BUYER_PERSIST AS
SELECT a.TICKER, a.TRADE_DATE, a.TOP_BUYER_CODE,
       COUNT(b.TRADE_DATE) AS TOP_BUYER_PERSISTENCE
FROM DAILY_BROKER_AGG a
LEFT JOIN DAILY_BROKER_AGG b
  ON b.TICKER = a.TICKER
 AND b.TOP_BUYER_CODE = a.TOP_BUYER_CODE
 AND b.TRADE_DATE <= a.TRADE_DATE
 AND b.TRADE_DATE > a.TRADE_DATE - 28
GROUP BY a.TICKER, a.TRADE_DATE, a.TOP_BUYER_CODE;
""")

# ---------- LAYER 2b ----------
con.execute("""
CREATE TABLE DAILY_PRICE_FEAT AS
WITH ret AS (
  SELECT TICKER, TRADE_DATE, CLOSE_PRICE, VALUE_IDR,
    CLOSE_PRICE / NULLIF(LAG(CLOSE_PRICE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE),0) - 1 AS RET_1D
  FROM DAILY_PRICE
)
SELECT TICKER, TRADE_DATE, CLOSE_PRICE, VALUE_IDR,
  LAG(CLOSE_PRICE,20) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE) AS CLOSE_LAG20,
  AVG(VALUE_IDR) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE
                       ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS AVG_VALUE_20D,
  STDDEV(RET_1D) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE
                       ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS VOL_20D,
  LEAD(CLOSE_PRICE,20) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE) AS CLOSE_FWD20
FROM ret;
""")

# ---------- LAYER 3 ----------
con.execute("""
CREATE TABLE SIG_ACCUMULATION AS
WITH joined AS (
  SELECT a.TICKER, a.TRADE_DATE, a.TOTAL_VALUE, a.FOREIGN_NET_VALUE, a.BUY_HHI,
         a.TOP_BUYER_CODE, p.TOP_BUYER_PERSISTENCE,
         f.CLOSE_PRICE, f.CLOSE_LAG20, f.AVG_VALUE_20D, f.VOL_20D, f.CLOSE_FWD20
  FROM DAILY_BROKER_AGG a
  JOIN DAILY_PRICE_FEAT f USING (TICKER, TRADE_DATE)
  JOIN TOP_BUYER_PERSIST p USING (TICKER, TRADE_DATE)
)
SELECT *,
  SUM(FOREIGN_NET_VALUE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS FOREIGN_NET_20D,
  AVG(BUY_HHI) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS HHI_20D,
  SUM(TOTAL_VALUE) OVER (PARTITION BY TICKER ORDER BY TRADE_DATE
      ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) AS TOTAL_VALUE_20D
FROM joined;
""")

# ---------- LAYER 4 ----------
con.execute("""
CREATE TABLE BANDAR_SCORE AS
WITH base AS (
  SELECT *, FOREIGN_NET_20D / NULLIF(TOTAL_VALUE_20D,0) AS ACCUM_INTENSITY,
            CLOSE_PRICE / NULLIF(CLOSE_LAG20,0) - 1 AS RET_20D,
            CLOSE_FWD20 / NULLIF(CLOSE_PRICE,0) - 1 AS FWD_RET_20D
  FROM SIG_ACCUMULATION
), ranked AS (
  SELECT *,
    PERCENT_RANK() OVER (PARTITION BY TRADE_DATE ORDER BY ACCUM_INTENSITY) AS R_ACCUM,
    PERCENT_RANK() OVER (PARTITION BY TRADE_DATE ORDER BY HHI_20D) AS R_CONC,
    PERCENT_RANK() OVER (PARTITION BY TRADE_DATE ORDER BY TOP_BUYER_PERSISTENCE) AS R_PERSIST,
    PERCENT_RANK() OVER (PARTITION BY TRADE_DATE ORDER BY -RET_20D) AS R_QUIET
  FROM base WHERE RET_20D IS NOT NULL
)
SELECT TICKER, TRADE_DATE, CLOSE_PRICE, ACCUM_INTENSITY, HHI_20D, TOP_BUYER_CODE,
       TOP_BUYER_PERSISTENCE, RET_20D, FWD_RET_20D, VOL_20D,
       ROUND(100*(0.40*R_ACCUM + 0.25*R_CONC + 0.20*R_PERSIST + 0.15*R_QUIET),2) AS BANDAR_SCORE,
       CASE
         WHEN 100*(0.40*R_ACCUM+0.25*R_CONC+0.20*R_PERSIST+0.15*R_QUIET) >= 85 THEN 'STEALTH_ACCUMULATION'
         WHEN 100*(0.40*R_ACCUM+0.25*R_CONC+0.20*R_PERSIST+0.15*R_QUIET) >= 70 THEN 'ACCUMULATION'
         WHEN 100*(0.40*R_ACCUM+0.25*R_CONC+0.20*R_PERSIST+0.15*R_QUIET) <= 15 THEN 'DISTRIBUTION'
         ELSE 'NEUTRAL' END AS SIGNAL_LABEL
FROM ranked;
""")

# ---------- LAYER 5 ----------
con.execute("""
CREATE TABLE SIGNAL_EDGE AS
SELECT SIGNAL_LABEL, COUNT(*) AS N_OBS,
       AVG(CASE WHEN FWD_RET_20D>0 THEN 1 ELSE 0 END) AS WIN_RATE,
       AVG(CASE WHEN FWD_RET_20D>0 THEN FWD_RET_20D END) AS AVG_WIN,
       ABS(AVG(CASE WHEN FWD_RET_20D<=0 THEN FWD_RET_20D END)) AS AVG_LOSS
FROM BANDAR_SCORE WHERE FWD_RET_20D IS NOT NULL GROUP BY SIGNAL_LABEL;
""")

print("\n--- SIGNAL_EDGE ---")
print(con.execute("SELECT * FROM SIGNAL_EDGE ORDER BY SIGNAL_LABEL").df().to_string(index=False))

# ---------- LAYER 6 Kelly ----------
print("\n--- POSITION SIZING (top 8) ---")
print(con.execute("""
WITH latest AS (
  SELECT * FROM BANDAR_SCORE
  QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKER ORDER BY TRADE_DATE DESC)=1
), kelly AS (
  SELECT l.TICKER, l.BANDAR_SCORE, l.SIGNAL_LABEL, l.TOP_BUYER_CODE, l.VOL_20D,
         e.N_OBS, e.WIN_RATE, e.AVG_WIN/NULLIF(e.AVG_LOSS,0) AS PAYOFF_B,
         ((e.AVG_WIN/NULLIF(e.AVG_LOSS,0))*e.WIN_RATE - (1-e.WIN_RATE))
           / NULLIF(e.AVG_WIN/NULLIF(e.AVG_LOSS,0),0) AS KELLY_FULL
  FROM latest l JOIN SIGNAL_EDGE e ON e.SIGNAL_LABEL=l.SIGNAL_LABEL
)
SELECT TICKER, BANDAR_SCORE, SIGNAL_LABEL, TOP_BUYER_CODE, N_OBS,
       ROUND(WIN_RATE,3) AS WIN_RATE, ROUND(PAYOFF_B,3) AS PAYOFF,
       ROUND(GREATEST(KELLY_FULL,0),4) AS KELLY_FULL,
       ROUND(LEAST(GREATEST(KELLY_FULL,0)*0.25
             * CASE WHEN N_OBS<100 THEN 0.5 ELSE 1.0 END
             * CASE WHEN VOL_20D>0.05 THEN 0.5 ELSE 1.0 END, 0.10),4) AS SUGGESTED_WEIGHT
FROM kelly ORDER BY BANDAR_SCORE DESC LIMIT 8
""").df().to_string(index=False))
