$queries = @(
@{name="stealth_accumulation_screen"; sql="SELECT TICKER, COMPANY_NAME, SECTOR, BANDAR_SCORE, PERSIST_DAYS_20D, RET_20D_PCT FROM MESSE.MART.VW_WATCHLIST WHERE SIGNAL_LABEL = 'STEALTH_ACCUMULATION' AND AVG_VALUE_20D >= 5000000000 ORDER BY BANDAR_SCORE DESC LIMIT 20;"},
@{name="persistent_accumulation_screen"; sql="SELECT TICKER, COMPANY_NAME, BANDAR_SCORE, PERSIST_DAYS_20D, RET_20D_PCT FROM MESSE.MART.VW_WATCHLIST WHERE SIGNAL_LABEL IN ('ACCUMULATION','STEALTH_ACCUMULATION') ORDER BY PERSIST_DAYS_20D DESC, BANDAR_SCORE DESC LIMIT 10;"},
@{name="sizing_with_real_edge"; sql="SELECT TICKER, SIGNAL_LABEL, BANDAR_SCORE, WIN_RATE, PAYOFF_RATIO, KELLY_FULL, SUGGESTED_WEIGHT, SIZING_CAVEAT, EDGE_SAMPLE_SIZE FROM MESSE.MART.VW_POSITION_SIZING WHERE SIZING_CAVEAT = 'OK' AND SUGGESTED_WEIGHT > 0 ORDER BY SUGGESTED_WEIGHT DESC LIMIT 20;"},
@{name="distribution_warning"; sql="SELECT TICKER, COMPANY_NAME, SECTOR, BANDAR_SCORE, RET_20D_PCT FROM MESSE.MART.VW_WATCHLIST WHERE SIGNAL_LABEL = 'DISTRIBUTION' ORDER BY BANDAR_SCORE ASC LIMIT 10;"},
@{name="honesty_beat_no_edge_disclosure"; sql="SELECT SIGNAL_LABEL, SIZING_CAVEAT, COUNT(*) AS N_TICKERS, AVG(WIN_RATE) AS AVG_WIN_RATE, AVG(KELLY_FULL) AS AVG_KELLY_FULL FROM MESSE.MART.VW_POSITION_SIZING GROUP BY SIGNAL_LABEL, SIZING_CAVEAT ORDER BY SIGNAL_LABEL;"}
)
foreach ($q in $queries) {
    Write-Output "=== $($q.name) ==="
    snow sql --connection messe -q $q.sql
    Write-Output ""
}
